export {
  homePreviewGlassGap,
  homePreviewGlassHeight,
  homePreviewGlassInset,
  homePreviewGlassOutlineInset,
  homePreviewGlassPaddingH,
  homePreviewGlassWidth,
  homeWidgetDisplaySize,
  homeWidgetPairWidth,
  homeWidgetPreviewScale,
  homeWidgetReferenceSize,
  homeWidgetStripHeight,
  homeWidgetStripPadding,
  standByOuterPad,
  standByWidgetGap,
  standByWidgetSize,
} from '../design-system';
